spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:./todo-app/todo-db'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
my.prop: 'test'